---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-app
    deployment: pks-workshop
  name: spring-boot-service
spec:
  ports:
  - port: 8080
    name: ui
    nodePort: 31529
  type: NodePort
  selector:
    app: spring-boot-app

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spring-boot-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      name: spring-boot
      labels:
        app: spring-boot-app
        deployment: pks-workshop
    spec:
      containers:
      - image: gcr.io/fe-bbyers/gs-spring-boot-docker:latest
        name: gs-spring-boot
        ports:
        - containerPort: 8080
          protocol: TCP
